version: '3.8'
services:
  consul-0:
    image: hashicorp/consul:1.15.4
    command: agent -server -bootstrap-expect=3 -node=consul-0 -bind=0.0.0.0 -client=0.0.0.0 -ui -data-dir=/consul/data -retry-join=consul-1 -retry-join=consul-2
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      - "8600:8600/tcp"
    networks:
      - consul-network
  consul-1:
    image: hashicorp/consul:1.15.4
    command: agent -server -node=consul-1 -bind=0.0.0.0 -client=0.0.0.0 -ui -data-dir=/consul/data -retry-join=consul-0 -retry-join=consul-2
    networks:
      - consul-network
  consul-2:
    image: hashicorp/consul:1.15.4
    command: agent -server -node=consul-2 -bind=0.0.0.0 -client=0.0.0.0 -ui -data-dir=/consul/data -retry-join=consul-0 -retry-join=consul-1
    networks:
      - consul-network
networks:
  consul-network:
