version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: contest_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
